; BIOS COLORS ;

; HEX CODE  COLOR 
; 00H       BLACK 
; 01H       BLUE 
; 02H       GREEN 
; 03H       CYAN 
; 04H       RED 
; 05H       MAGENTA 
; 06H       BROWN 
; 07H       LIGHT GRAY 
; 08H       DARK GRAY 
; 09H       LIGHT BLUE 
; 0AH       LIGHT GREEN 
; 0BH       LIGHT CYAN 
; 0CH       LIGHT RED 
; 0DH       LIGHT MAGENTA 
; 0EH       YELLOW 
; 0FH       WHITE 

; SYSTEM TIME ;

; REGISTER  SYSTEM TIME
; CH	    HOUR
; CL        MINUTE
; DH        SECOND
; DL        1/100 SECONDS

; ASCII CHARACTERS ;
; LINK: https://www.asciitable.com/

;------------------------------------------------------------------;

STACK SEGMENT PARA STACK

    DB 64 DUP (' ')

STACK ENDS

DATA SEGMENT PARA 'DATA' ; DEFINE VARIABLES HERE.

; SYSTEM VARIABLES:

    VIDEO_MODE       DB 13H  ; VIDEO MODE: (320 x 200) AND 256 COLORS.
    WINDOW_WIDTH     DW 140H ; 320px.
    WINDOW_HEIGHT    DW 0C8H ; 200px.
    BORDER_FIX       DW 02H  ; TO FIX COLISSION WITH WINDOW BORDERS.
    BACKGROUND_COLOR DB 00H  ; BLACK.
    PIXEL_COLOR      DB 0FH  ; WHITE.
    TIME_AUX         DB 00H  
	GAME_ACTIVE	     DB 01H  ; 
	EXITING_PROGRAM  DB 00H  ; BOOL.
	CURRENT_SCENE    DB 00H  
	MAX_SCORE        DB 0AH ; SCORE TO WIN: 10PTS.
	WINNER_INDEX     DB 00H  
	
; TEXT VARIABLES:

; GENERAL: 

	TEXT_X                    DB 00H
	TEXT_Y                    DB 00H
	TEXT_MAIN_MENU_TITLE      DB 'MAIN MENU', '$'                      
	TEXT_GAME_TITLE           DB 'SPACE RACE', '$'                      
	TEXT_SINGLEPLAYER         DB 'PRESS S FOR SINGLEPLAYER', '$'       
	TEXT_MULTIPLAYER          DB 'PRESS A FOR MULTIPLAYER', '$'        
	TEXT_EXIT_GAME            DB 'PRESS M TO EXIT', '$'	
	TEXT_GAME_OVER_TITLE      DB 'GAME OVER', '$'                      
	TEXT_GAME_OVER_WINNER     DB 'PLAYER ? WINS!', '$'                 
	TEXT_PLAY_AGAIN_GAME_OVER DB 'PRESS R TO PLAY AGAIN', '$'          
	TEXT_MAIN_MENU_GAME_OVER  DB 'PRESS M TO RETURN TO MAIN MENU', '$' 	
	TEXT_HAPPY_BIRTHDAY       DB 'HAPPY BIRTHDAY!', '$'		   

; SHIPS:

	TEXT_LEFT_SHIP_POINTS  DB '0', '$' ; TO DISPLAY LEFT SHIP POINT ON SCREEN.
	TEXT_RIGHT_SHIP_POINTS DB '0', '$' ; TO DISPLAY RIGHT SHIP POINT ON SCREEN.

; TIME BAR:

	TIME_BAR_X              DW 9DH
	TIME_BAR_Y              DW 00H
	TIME_BAR_HEIGHT         DW 0C8H
	TIME_BAR_SPEED          DW 01H
	TIME_BAR_WIDTH          DW 06H
	TIME_BAR_CRITICAL       DW 19H    
	TIME_BAR_COLOR          DB 02H  ; GREEN.
	TIME_BAR_COLOR_CRITICAL DB 04H  ; RED.
	TIME_BAR_COUNTER        DW 00H
	TIME_BAR_INTERVAL       DW 03H  ; UPDATE THE BAR EVERY 4 FRAMES.

; METEOR VARIABLES:

	NUM_METEORS        DW 05H                        ; NUMBER OF METEORS.
    METEOR_INDEX       DW 00H                        ; VARIABLE TO GO THROUGH ALL METEORS.
    METEOR_X_ARRAY     DW 20H, 60H, 0A0H, 0E0H, 100H ; ARRAY WITH X POSITIONS.
    METEOR_Y_ARRAY     DW 20H, 40H, 60H, 80H, 0A0H   ; ARRAY WITH Y POSITIONS.
    METEOR_SPEED_ARRAY DW 02H, 03H, 02H, 04H, 03H    ; ARRAY WITH SPEED FOR EACH METEOR.
    METEOR_DIR_ARRAY   DW 01H, 0FFH, 01H, 0FFH, 01H  ; DIRECTIONS FOR EACH METEOR.
    METEOR_SIZE        DW 02H
    METEOR_COLOR       DB 08H                        ; DARK GRAY

; SHIP VARIABLES:

; GENERAL VARIABLES:
   
    SHIP_WIDTH  DW 05H
    SHIP_HEIGHT DW 07H
	SHIP_COLOR  DB 07H ; LIGHT GRAY.
	SHIP_SPEED  DW 05H

; LEFT SHIP:

	SHIP_LEFT_X_INIT DW 50H  ; INITIAL X POSITION.
	SHIP_LEFT_Y_INIT DW 0B4H ; INITIAL Y POSITION.
    SHIP_LEFT_X      DW 50H  ; CURRENT X POSITION.
    SHIP_LEFT_Y      DW 0B4H ; CURRENT Y POSITION.
	LEFT_SHIP_POINTS DB 00H

; RIGHT SHIP:

	SHIP_RIGHT_X_INIT DW 10EH
	SHIP_RIGHT_Y_INIT DW 0B4H
    SHIP_RIGHT_X      DW 10EH
    SHIP_RIGHT_Y      DW 0B4H
	RIGHT_SHIP_POINTS DB 00H
	AI_CONTROLLED     DB 00H  ; CHECK IF RIGHT SHIP IS CONTROLLED BY AI.

DATA ENDS

;------------------------------------------------------------------;

; MAIN PROCEDURE ;

CODE SEGMENT PARA 'CODE'
    
    MAIN PROC FAR

; ASSUME CODE, DATA AND STACK SEGMENTS THEIR RESPECTIVE REGISTERS.

    ASSUME CS: CODE, DS: DATA, SS: STACK

    PUSH DS       ; PUSH THE DS SEGMENT TO STACK.
    SUB  AX, AX   ; CLEAN THE AX REGISTER.
    PUSH AX       ; PUSH AX TO THE STACK.
    MOV  AX, DATA ; MOVE TO THE AX REGISTER THE CONTENTS OF THE DATA SEGMENT.
    MOV  DS, AX   ; MOVE TO THE DATA SEGMENT THE CONTENTS OF THE AX REGISTER.
    POP  AX       ; MOVE THE TOP ITEM FROM THE STACK INTO THE AX REGISTER.
    POP  AX

	CALL CLEAR_WINDOW

; THE INTERRUPTION THAT ALLOWS TO GET SYSTEM IS: 21H.
; GETTING SYSTEM TIME:

	CHECK_TIME:

		CMP EXITING_PROGRAM, 01H ; CHECK IF THE PROGRAM SHOULD EXIT.

		JE EXIT_PROCESS ; EXIT THE PROGRAM

		CMP CURRENT_SCENE, 00H
		
		JE SHOW_MAIN_MENU
	
		CMP GAME_ACTIVE, 00H
		
		JE SHOW_GAME_OVER

		CMP GAME_ACTIVE, 02H

		JE SHOW_HAPPY_BIRTHDAY

	    MOV AH , 2CH      ; SETTING FOR GETTING SYSTEM TIME.
	    INT 21H           ; EXECUTION TO EXECUTE THE CONFIGURATION.
	    CMP DL , TIME_AUX ; COMPARE TIME_AUX WITH THE DL REGISTER (1/100 SECONDS).

	    JE CHECK_TIME ; JUMP IF TIME_AUX = 1/100 SECONDS.

	    MOV TIME_AUX, DL ; COUNT TIME.

; CALLS TO PROCEDURES:

	    CALL CLEAR_WINDOW
	    CALL MOVE_SHIPS 
		CALL DRAW_ALL_METEORS
	    CALL DRAW_SHIPS
		CALL TIME_BAR_UPDATE
		CALL MOVE_ALL_METEORS
		CALL DRAW_UI      

	    JMP CHECK_TIME ; RESTART CLOCK CYCLE.

		SHOW_HAPPY_BIRTHDAY:

			CALL DRAW_HAPPY_BIRTHDAY

			JMP CHECK_TIME
		
		SHOW_GAME_OVER:

			CALL DRAW_GAME_OVER_MENU
			
			JMP CHECK_TIME

		SHOW_MAIN_MENU:

			CALL DRAW_MAIN_MENU
			
			JMP CHECK_TIME

		EXIT_PROCESS:

			CALL EXIT_MAIN_PROGRAM

        RET

    MAIN ENDP

;------------------------------------------------------------------;

; SYSTEM PROCEDURES ;

; INITIALIZING GRAPHICS MODE:

    GRAPHICS_MODE PROC NEAR

; INTERRUPTION TO ENTER GRAPHICS MODE: 10H.
; THE 10H INTERRUPTION PROVIDES VIDEO SERVICES, SETTINGS FOR VIDEO MODE AND PIXEL DRAWING IN GRAPHICS MODE.

        MOV AH , 00H        ; SETTING FOR CONFIGURATION.
        MOV AL , VIDEO_MODE ; SETTING VIDEO MODE (320 x 200) AND 256 COLORS.
        INT 10H             ; INTERRUPTION TO EXECUTE THE CONFIGURATION.

        RET

    GRAPHICS_MODE ENDP

; COLORING THE BACKGROUND:

    SET_BACKGROUND PROC NEAR ; (USE WITH GRAPHICS_MODE PROC).

        MOV AH, 0BH              ; SETTING FOR CONFIGURATION.
        MOV BH, 02H              ; SETTING BACKGROUND COLOR.
        MOV BL, BACKGROUND_COLOR ; COLORING THE BACKGROUND. 
 
        RET

    SET_BACKGROUND ENDP

    DRAW_PIXEL PROC NEAR

        MOV AH , 0CH         ; SETTING FOR CONFIGURATION.
        MOV AL , PIXEL_COLOR
        MOV BH , 00H         ; SETTING THE PAGE NUMBER.
        INT 10H

        RET

    DRAW_PIXEL ENDP

; CLEARING THE WINDOW:

    CLEAR_WINDOW PROC NEAR

       CALL GRAPHICS_MODE
       CALL SET_BACKGROUND

       RET

    CLEAR_WINDOW ENDP

; CHECKING IF A KEY IS BEING PRESSED:

    KEY_PRESS PROC NEAR

; KEYBOARD BIOS SERVICES: INT 16H.
; THE INT 16H OFFERS DIFFERENT KEYBOARD RELATED PROCEDURES AND ALLOWS TO GET KEYBOARD STATE.

    	MOV AH , 01H ; TO GET KEYBOARD STATUS.
		INT 16H      ; INTERRUPTION TO EXECUTE CONFIGURATION.

        RET

    KEY_PRESS ENDP

; RETURNING PRESSED KEY:

    RETURN_KEY PROC NEAR

    	MOV AH , 00H ; WAIT FOR KEYPRESS AND READ CHARACTER.
		INT 16H

        RET

    RETURN_KEY ENDP
	
; PRINTING TEXT ON SCREEN:

	PRINT_TEXT PROC NEAR
	
		MOV AH , 02H    ; SET CURSOR POSITION.
		MOV BH , 00H
		MOV DH , TEXT_Y
		MOV DL , TEXT_X
		INT 10H

		RET
	
	PRINT_TEXT ENDP

	EXIT_MAIN_PROGRAM PROC NEAR

		MOV AH, 00H
		MOV AL, 00H
		INT 10H
		
		MOV AH, 4CH
		INT 21H

	EXIT_MAIN_PROGRAM ENDP

;------------------------------------------------------------------;

; GAME PROCEDURES ;

; DRAWING TIME BAR:

	DRAW_TIME_BAR PROC NEAR

		MOV CX, TIME_BAR_X
		MOV DX, TIME_BAR_Y

		MOV AL, TIME_BAR_COLOR
		MOV PIXEL_COLOR, AL
		
		DRAW_TIME_BAR_LOOP:

			CALL DRAW_PIXEL

			INC CX
			MOV AX, CX
			SUB AX, TIME_BAR_X
			CMP AX, TIME_BAR_WIDTH

			JNG DRAW_TIME_BAR_LOOP

			MOV CX, TIME_BAR_X
			INC DX
			MOV AX, DX
			SUB AX, TIME_BAR_Y
			CMP AX, TIME_BAR_HEIGHT

			JNG DRAW_TIME_BAR_LOOP

		RET

	DRAW_TIME_BAR ENDP

; UPDATING TIME BAR:

	TIME_BAR_UPDATE PROC NEAR ; TO UPDATE THE TIME BAR IS NECESSARY TO HAVE A DELAY BECAUSE OF HOW FAST THE TIME LOOP UPDATES.

			CALL DRAW_TIME_BAR

			INC TIME_BAR_COUNTER
			MOV AX, TIME_BAR_COUNTER
    		CMP AX, TIME_BAR_INTERVAL

			JB TIME_SKIP

			MOV TIME_BAR_COUNTER, 00H
			MOV AX, TIME_BAR_HEIGHT
			SUB AX, TIME_BAR_SPEED
			MOV TIME_BAR_HEIGHT, AX

			CMP TIME_BAR_HEIGHT, 00H

			JE OUT_OF_TIME

			CMP TIME_BAR_HEIGHT, 1FH
			
			JE CHANGE_BAR_COLOR

			RET

			CHANGE_BAR_COLOR:

				MOV TIME_BAR_COLOR, 04H
				MOV AL, TIME_BAR_COLOR
				MOV PIXEL_COLOR, AL

				RET

			TIME_SKIP:
			
				RET
			
			OUT_OF_TIME:

				CALL GAME_OVER

	TIME_BAR_UPDATE ENDP

; DRAWING METEORS:

	DRAW_ALL_METEORS PROC NEAR

		MOV METEOR_INDEX, 00H

		DRAW_METEORS_LOOP:

			MOV SI         , METEOR_INDEX            
			SHL SI         , 1       
			MOV CX         , [METEOR_X_ARRAY + SI]
			MOV DX         , [METEOR_X_ARRAY + SI]
			MOV AL         , METEOR_COLOR
			MOV PIXEL_COLOR, AL
			PUSH CX
			PUSH DX
			
			DRAW_SINGLE_METEOR:

				CALL DRAW_PIXEL

				INC CX
				MOV AX , CX
				POP BX
				PUSH BX
				SUB AX , BX
				CMP AX , METEOR_SIZE

				JNG DRAW_SINGLE_METEOR
				
				POP BX
				PUSH BX
				MOV CX , BX
				INC DX
				MOV AX , DX
				MOV BX , [METEOR_X_ARRAY + SI]
				SUB AX , BX
				CMP AX , METEOR_SIZE
				
				JNG DRAW_SINGLE_METEOR
			
			POP DX
			POP CX

			INC METEOR_INDEX
			MOV AX          , METEOR_INDEX
			CMP AX          , NUM_METEORS

			JL DRAW_METEORS_LOOP

		RET

	DRAW_ALL_METEORS ENDP

; MOVING METEORS:

	MOVE_ALL_METEORS PROC NEAR

		MOV METEOR_INDEX, 00H

		MOVE_METEORS_LOOP:
			
			MOV SI, METEOR_INDEX
			SHL SI, 1                       
			
			MOV AX, [METEOR_SPEED_ARRAY + SI]
			MOV BX, [METEOR_DIR_ARRAY + SI]
			CMP BX, 0FFH

			JE MOVE_LEFT_DIR
		
			ADD [METEOR_X_ARRAY + SI], AX

			JMP CHECK_METEOR_BOUNDS
			
			MOVE_LEFT_DIR:

				SUB [METEOR_X_ARRAY + SI], AX
			
			CHECK_METEOR_BOUNDS:


				MOV AX, [METEOR_X_ARRAY + SI]
				ADD AX, METEOR_SIZE
				CMP AX, WINDOW_WIDTH

				JGE REVERSE_METEOR_DIR
				
				MOV AX, [METEOR_X_ARRAY + SI]
				CMP AX, 00H

				JLE REVERSE_METEOR_DIR
				
				JMP CHECK_SHIP_COLLISIONS
			
			REVERSE_METEOR_DIR:

				NEG WORD PTR [METEOR_DIR_ARRAY + SI]
				XOR [METEOR_DIR_ARRAY + SI]         , 0FFFEH
			
			CHECK_SHIP_COLLISIONS:

				CALL CHECK_METEOR_LEFT_SHIP_COLLISION
				CALL CHECK_METEOR_RIGHT_SHIP_COLLISION
			
			INC METEOR_INDEX
			MOV AX          , METEOR_INDEX
			CMP AX          , NUM_METEORS

			JL MOVE_METEORS_LOOP

		RET

	MOVE_ALL_METEORS ENDP

; CHECKING FOR COLLISIONS:

; CHECKING LEFT SHIP COLISSION

	CHECK_METEOR_LEFT_SHIP_COLLISION PROC NEAR

		MOV SI, METEOR_INDEX
		SHL SI, 1
		MOV AX, [METEOR_X_ARRAY + SI]
		MOV BX, [METEOR_X_ARRAY + SI]
		
; CHECKING IF X IS COLLISIONING:

		MOV CX, SHIP_LEFT_X
		ADD CX, SHIP_WIDTH
		CMP AX, CX       

		JGE NO_LEFT_COLLISION
		
		ADD AX, METEOR_SIZE
		CMP AX, SHIP_LEFT_X      
		
		JLE NO_LEFT_COLLISION
		
; CHECK IF Y IS COLLISIONING:

		MOV CX, SHIP_LEFT_Y
		ADD CX, SHIP_HEIGHT
		CMP BX, CX               

		JGE NO_LEFT_COLLISION
		
		ADD BX, METEOR_SIZE
		CMP BX, SHIP_LEFT_Y           

		JLE NO_LEFT_COLLISION
		
		CALL RESET_LEFT_SHIP
		
		NEG WORD PTR [METEOR_DIR_ARRAY + SI]

		RET
		
		NO_LEFT_COLLISION:

			RET

	CHECK_METEOR_LEFT_SHIP_COLLISION ENDP

; CHECKING RIGHT SHIP COLLISION

	CHECK_METEOR_RIGHT_SHIP_COLLISION PROC NEAR

		MOV SI, METEOR_INDEX
		SHL SI, 1
		MOV AX, [METEOR_X_ARRAY + SI]
		MOV BX, [METEOR_X_ARRAY + SI]
		MOV CX, SHIP_RIGHT_X
		ADD CX, SHIP_WIDTH
		CMP AX, CX

		JGE NO_RIGHT_COLLISION
		
		ADD AX, METEOR_SIZE
		CMP AX, SHIP_RIGHT_X

		JLE NO_RIGHT_COLLISION
		
		; CHECK Y OVERLAP
		MOV CX, SHIP_RIGHT_Y
		ADD CX, SHIP_HEIGHT
		CMP BX, CX
		JGE NO_RIGHT_COLLISION
		
		ADD BX, METEOR_SIZE
		CMP BX, SHIP_RIGHT_Y
		JLE NO_RIGHT_COLLISION
		
		CALL RESET_RIGHT_SHIP
		
		NEG WORD PTR [METEOR_DIR_ARRAY + SI]

		RET
		
		NO_RIGHT_COLLISION:

			RET

	CHECK_METEOR_RIGHT_SHIP_COLLISION ENDP

; RESETTING THE SHIPS:

; RESETTING LEFT SHIP:

    RESET_LEFT_SHIP PROC NEAR

		MOV AX         , SHIP_LEFT_X_INIT
		MOV SHIP_LEFT_X, AX             
		MOV AX         , SHIP_LEFT_Y_INIT 
		MOV SHIP_LEFT_Y, AX             

    	RET

    RESET_LEFT_SHIP ENDP
	
; RESETTING RIGHT SHIP
	
	RESET_RIGHT_SHIP PROC NEAR

		MOV AX          , SHIP_RIGHT_X_INIT
		MOV SHIP_RIGHT_X, AX             
		MOV AX          , SHIP_RIGHT_Y_INIT 
		MOV SHIP_RIGHT_Y, AX             

    	RET

    RESET_RIGHT_SHIP ENDP

; MOVING THE SHIPS:

    MOVE_SHIPS PROC NEAR

        CALL KEY_PRESS  ; CHECK IF A KEY IS BEING PRESSED.
	
		JZ CHECK_RIGHT_SHIP_MOV

		CALL RETURN_KEY ; RETURN PRESSED KEY.

; MOVING THE LEFT SHIP:

		CMP AL, 77H ; CHECK IF PRESSED KEY IS 'w'.

		JE MOVE_LEFT_SHIP_UP ; JUMP IF ASCII CHARACTER IS EQUAL TO 77H (w).

		CMP AL, 57H ; CHECK IF PRESSED KEY IS 'W'

		JE MOVE_LEFT_SHIP_UP

		CMP AL, 73H ; CHECK IF PRESSED KEY IS 's'.

		JE MOVE_LEFT_SHIP_DOWN ; JUMP IF ASCII CHARACTER IS EQUAL TO 73H (s).

		CMP AL, 53H ; CHECK IF PRESSED KEY IS 'S'

		JE MOVE_LEFT_SHIP_DOWN

		JMP CHECK_RIGHT_SHIP_MOV ; JUMP TO CHECK RIGHT SHIP MOVEMENT.

		MOVE_LEFT_SHIP_UP:

			MOV AX          , SHIP_SPEED ; STORE SHIP_SPEED IN AX.
			SUB SHIP_LEFT_Y , AX         ; MOVE SHIP UP.
			MOV AX          , BORDER_FIX
			CMP SHIP_LEFT_Y , AX

			JL CHECK_LEFT_SHIP_TOP

			JMP CHECK_RIGHT_SHIP_MOV

			CHECK_LEFT_SHIP_TOP:

				INC LEFT_SHIP_POINTS

				CALL RESET_LEFT_SHIP
				CALL UPDATE_TEXT_LEFT_SHIP_POINTS

				CMP LEFT_SHIP_POINTS, 0AH

				JGE END_GAME

				JMP CHECK_RIGHT_SHIP_MOV

		MOVE_LEFT_SHIP_DOWN:

			MOV AX         , SHIP_SPEED    ; STORE SHIP_SPEED IN AX.
			ADD SHIP_LEFT_Y, AX            ; MOVE SHIP UP.
			MOV AX         , WINDOW_HEIGHT
			SUB AX         , BORDER_FIX
			SUB AX         , SHIP_HEIGHT
			CMP SHIP_LEFT_Y, AX

			JG FIX_LEFT_SHIP_BOTTOM

			JMP CHECK_RIGHT_SHIP_MOV

			FIX_LEFT_SHIP_BOTTOM:

				MOV SHIP_LEFT_Y, AX

				JMP CHECK_RIGHT_SHIP_MOV

	; MOVING THE RIGHT SHIP:

		CHECK_RIGHT_SHIP_MOV:

			CMP AI_CONTROLLED, 01H

			JE IS_CONTROLLED_BY_AI

			CMP AL, 6FH ; CHECK IF PRESSED KEY IS 'o'.

			JE MOVE_RIGHT_SHIP_UP ; JUMP IF ASCII CHARACTER IS EQUAL TO 6FH (S).

			CMP AL, 4FH ; CHECK IF PRESSED KEY IS 'O'

			JE MOVE_RIGHT_SHIP_UP

			CMP AL, 6CH ; CHECK IF PRESSED KEY IS 'l'.

			JE MOVE_RIGHT_SHIP_DOWN ; JUMP IF ASCII CHARACTER IS EQUAL TO 6CH (s).

			CMP AL, 4CH ; CHECK IF PRESSED KEY IS 'L'

			JE MOVE_RIGHT_SHIP_DOWN

			JMP EXIT_MOVE_SHIPS ; JUMP TO CHECK LEFT SHIP MOVEMENT.

			IS_CONTROLLED_BY_AI:

				JMP MOVE_RIGHT_SHIP_UP
				
				RET

			END_GAME:

				CALL DRAW_HAPPY_BIRTHDAY

				RET

			MOVE_RIGHT_SHIP_UP:

				MOV AX          , SHIP_SPEED ; STORE SHIP_SPEED IN AX.
				SUB SHIP_RIGHT_Y, AX         ; MOVE SHIP UP.
				MOV AX          , BORDER_FIX
				CMP SHIP_RIGHT_Y, AX

				JL CHECK_RIGHT_SHIP_TOP

				JMP EXIT_MOVE_SHIPS

				CHECK_RIGHT_SHIP_TOP:

					INC RIGHT_SHIP_POINTS

					CALL RESET_RIGHT_SHIP
					CALL UPDATE_TEXT_RIGHT_SHIP_POINTS

					CMP RIGHT_SHIP_POINTS, 0AH

					JGE END_GAME

					JMP EXIT_MOVE_SHIPS

			MOVE_RIGHT_SHIP_DOWN:

				MOV AX          , SHIP_SPEED ; STORE SHIP_SPEED IN AX.
				ADD SHIP_RIGHT_Y, AX         ; MOVE SHIP UP.
				MOV AX          , WINDOW_HEIGHT
				SUB AX          , BORDER_FIX
				SUB AX          , SHIP_HEIGHT
				CMP SHIP_RIGHT_Y, AX

				JG FIX_RIGHT_SHIP_BOTTOM

				JMP EXIT_MOVE_SHIPS

				FIX_RIGHT_SHIP_BOTTOM:

					MOV SHIP_RIGHT_Y, AX

					JMP EXIT_MOVE_SHIPS

			EXIT_MOVE_SHIPS:
		
				RET

    MOVE_SHIPS ENDP

; DRAWING THE SHIPS:

	DRAW_SHIPS PROC NEAR

		MOV CX, SHIP_LEFT_X ; STORE IN CX REGISTER THE X POSITION OF THE LEFT SHIP.
		MOV DX, SHIP_LEFT_Y ; STORE IN DX REGISTER THE Y POSITION OF THE LEFT SHIP.

; CHANGING SHIP COLOR:

		MOV AL, SHIP_COLOR
		MOV PIXEL_COLOR, AL

		DRAW_SHIP_LEFT:

			CALL DRAW_PIXEL

			INC CX              ; INCREMENT IN 1 THE X POSITION OF THE LEFT SHIP. 
			MOV AX, CX          ; MOVE THE CONTENTS OF CX REGISTER INTO THE AX REGISTER.
			SUB AX, SHIP_LEFT_X ; SUBTRACT THE VALUE STORED IN METEOR_X FROM NEW SHIP_LEFT_X.
			CMP AX, SHIP_WIDTH  ; COMPARE THE SUB RESULT TO THE SHIP SIZE.

			JNG DRAW_SHIP_LEFT ; JUMP IF SHIP_LEFT_X IS LOWER THAN SHIP_WIDTH.
		
			MOV CX, SHIP_LEFT_X ; RESET SHIP_LEFT_X POSITION. 
			INC DX              ; INCREMENT IN 1 THE Y POSITION OF THE LEFT SHIP.

			MOV AX, DX
			SUB AX, SHIP_LEFT_Y
			CMP AX, SHIP_HEIGHT

			JNG DRAW_SHIP_LEFT

			MOV CX, SHIP_RIGHT_X
			MOV DX, SHIP_RIGHT_Y

		DRAW_SHIP_RIGHT:
		
			CALL DRAW_PIXEL 

			INC CX            
			MOV AX, CX       
			SUB AX, SHIP_RIGHT_X 
			CMP AX, SHIP_WIDTH

			JNG DRAW_SHIP_RIGHT
		
			MOV CX, SHIP_RIGHT_X
			INC DX

			MOV AX, DX
			SUB AX, SHIP_RIGHT_Y
			CMP AX, SHIP_HEIGHT

			JNG DRAW_SHIP_RIGHT

		RET

	DRAW_SHIPS ENDP

; DRAWING GAME UI:
	
	DRAW_UI PROC NEAR

; DRAWING THE LEFT SHIP POINTS ON SCREEN:

		MOV TEXT_X, 06H
		MOV TEXT_Y, 04H
		
		CALL PRINT_TEXT
		
		MOV AH , 09                   
		LEA DX , TEXT_LEFT_SHIP_POINTS
		INT 21H

; DRAWING THE RIGHT SHIP POINTS ON SCREEN:

		MOV TEXT_X, 1FH
		MOV TEXT_Y, 04H

		CALL PRINT_TEXT

		MOV AH , 09                    ;
		LEA DX , TEXT_RIGHT_SHIP_POINTS
		INT 21H

		RET

	DRAW_UI ENDP

; UPDATING WINNER TEXT:

	UPDATE_WINNER_TEXT PROC NEAR

		MOV AL                         , WINNER_INDEX
		ADD AL                         , 30H
		MOV [TEXT_GAME_OVER_WINNER + 7], AL

		RET

	UPDATE_WINNER_TEXT ENDP

; DRAWING THE GAME OVER MENU:

	DRAW_GAME_OVER_MENU PROC NEAR

		CALL CLEAR_WINDOW
		
; DRAWING 'GAME OVER' TEXT:

		MOV TEXT_X, 0FH
		MOV TEXT_Y, 01H

		CALL PRINT_TEXT

		MOV AH , 09                   ; WRITE TO STANDARD OUTPUT
		LEA DX , TEXT_GAME_OVER_TITLE
		INT 21H


; DRAWING WINNER TEXT:

		MOV TEXT_X, 0DH
		MOV TEXT_Y, 03H

		CALL PRINT_TEXT

		CALL UPDATE_WINNER_TEXT

		MOV AH , 09                    
		LEA DX , TEXT_GAME_OVER_WINNER
		INT 21H

; DRAWING RESTART GAME TEXT:

		MOV TEXT_X, 09H
		MOV TEXT_Y, 0FH

		CALL PRINT_TEXT

		MOV AH , 09            
		LEA DX , TEXT_PLAY_AGAIN_GAME_OVER
		INT 21H
		
; DRAWING RETURN TO MAIN MENU TEXT:

		MOV TEXT_X, 05H
		MOV TEXT_Y, 11H

		CALL PRINT_TEXT

		MOV AH , 09              
		LEA DX , TEXT_MAIN_MENU_GAME_OVER
		INT 21H

; WATING FOR KEY PRESS:

		CALL RETURN_KEY
		
		CMP AL, 'R'

		JE RESTART_GAME

		CMP AL, 'r'

		JE RESTART_GAME
		
		CMP AL, 'M'
		
		JE MAIN_MENU

		CMP AL, 'm'
		
		JE MAIN_MENU

		RET

		MAIN_MENU:

			MOV GAME_ACTIVE  , 00H
			MOV CURRENT_SCENE, 00H

			CALL DRAW_MAIN_MENU

			RET

		RESTART_GAME:

			MOV GAME_ACTIVE, 01H

			RET

	DRAW_GAME_OVER_MENU ENDP
	
	DRAW_MAIN_MENU PROC NEAR
	
		CALL CLEAR_WINDOW

		MOV TEXT_X, 0EH
		MOV TEXT_Y, 01H
		MOV BL, 02H
		CALL PRINT_TEXT

		MOV AH , 09
		LEA DX , TEXT_GAME_TITLE
		INT 21H
		
		MOV TEXT_X, 0FH	
		MOV TEXT_Y, 05H

		CALL PRINT_TEXT

		MOV AH, 09           
		LEA DX, TEXT_MAIN_MENU_TITLE
		INT 21H

		MOV TEXT_X, 08H
		MOV TEXT_Y, 08H

		CALL PRINT_TEXT

		MOV AH , 09           
		LEA DX , TEXT_SINGLEPLAYER
		INT 21H

		MOV TEXT_X, 08H
		MOV TEXT_Y, 0BH

		CALL PRINT_TEXT

		MOV AH , 09              
		LEA DX , TEXT_MULTIPLAYER
		INT 21H

		MOV TEXT_X, 0BH
		MOV TEXT_Y, 15H

		CALL PRINT_TEXT

		MOV AH , 09           
		LEA DX , TEXT_EXIT_GAME
		INT 21H

		CALL RETURN_KEY

		CMP AL, 'M'
		
		JE EXIT_PROGRAM
		
		CMP AL, 'm'

		JE EXIT_PROGRAM

		CMP AL, 'S'
		
		JE SINGLEPLAYER_MODE
		
		CMP AL, 's'

		JE SINGLEPLAYER_MODE

		CMP AL, 'A'
		
		JE MULTIPLAYER_MODE
		
		CMP AL, 'a'

		JE MULTIPLAYER_MODE

		EXIT_PROGRAM:

			MOV EXITING_PROGRAM, 01H

			RET

		SINGLEPLAYER_MODE:

			MOV AI_CONTROLLED, 01H
			MOV CURRENT_SCENE, 01H
			MOV GAME_ACTIVE  , 01H
			
			RET

		MULTIPLAYER_MODE:

			MOV AI_CONTROLLED, 00H
			MOV CURRENT_SCENE, 01H
			MOV GAME_ACTIVE  , 01H
			
			RET

	DRAW_MAIN_MENU ENDP
	
	UPDATE_TEXT_LEFT_SHIP_POINTS PROC NEAR

		XOR AX                     , AX
		MOV AL                     , LEFT_SHIP_POINTS
		ADD AL                     , 30H ; CONVERT FROM NUMBER TO ASCII
		MOV [TEXT_LEFT_SHIP_POINTS], AL

		RET

	UPDATE_TEXT_LEFT_SHIP_POINTS ENDP
	
	UPDATE_TEXT_RIGHT_SHIP_POINTS PROC NEAR

		XOR AX                      , AX
		MOV AL                      , RIGHT_SHIP_POINTS
		ADD AL                      , 30H ; CONVERT FROM NUMBER TO ASCII
		MOV [TEXT_RIGHT_SHIP_POINTS], AL

		RET

	UPDATE_TEXT_RIGHT_SHIP_POINTS ENDP

; GAME OVER:

	GAME_OVER PROC NEAR

		MOV AH              , RIGHT_SHIP_POINTS
		CMP LEFT_SHIP_POINTS, AH
		
		JNL SHIP_LEFT_WINS

		JMP SHIP_RIGHT_WINS
		
		SHIP_LEFT_WINS:

			MOV WINNER_INDEX, 01H

			JMP CONTINUE_GAME_OVER

		SHIP_RIGHT_WINS:

			MOV WINNER_INDEX, 02H

		    JMP CONTINUE_GAME_OVER
		
		CONTINUE_GAME_OVER:

			MOV LEFT_SHIP_POINTS , 00H
			MOV RIGHT_SHIP_POINTS, 00H

			MOV SHIP_LEFT_X    , 50H
			MOV SHIP_RIGHT_X   , 10EH
			MOV SHIP_LEFT_Y    , 0B4H
			MOV SHIP_RIGHT_Y   , 0B4H
			MOV TIME_BAR_HEIGHT, 0C8H
			MOV TIME_BAR_COLOR , 02H

			CALL UPDATE_TEXT_LEFT_SHIP_POINTS
			CALL UPDATE_TEXT_RIGHT_SHIP_POINTS

			MOV GAME_ACTIVE, 00H
		
			RET

	GAME_OVER ENDP

	DRAW_HAPPY_BIRTHDAY PROC NEAR
	
		CALL CLEAR_WINDOW

; DRAWING WINNER TEXT:

		MOV TEXT_X, 0DH
		MOV TEXT_Y, 03H

		CALL PRINT_TEXT

		CALL UPDATE_WINNER_TEXT

		MOV AH , 09                    
		LEA DX , TEXT_HAPPY_BIRTHDAY
		INT 21H

; DRAWING RESTART GAME TEXT:

		MOV TEXT_X, 09H
		MOV TEXT_Y, 0FH

		CALL PRINT_TEXT

		MOV AH , 09            
		LEA DX , TEXT_PLAY_AGAIN_GAME_OVER
		INT 21H
		
; DRAWING RETURN TO MAIN MENU TEXT:

		MOV TEXT_X, 05H
		MOV TEXT_Y, 11H

		CALL PRINT_TEXT

		MOV AH , 09              
		LEA DX , TEXT_MAIN_MENU_GAME_OVER
		INT 21H

		MOV LEFT_SHIP_POINTS , 00H
		MOV RIGHT_SHIP_POINTS, 00H

		MOV SHIP_LEFT_X    , 50H
		MOV SHIP_RIGHT_X   , 10EH
		MOV SHIP_LEFT_Y    , 0B4H
		MOV SHIP_RIGHT_Y   , 0B4H
		MOV TIME_BAR_HEIGHT, 0C8H

		CALL UPDATE_TEXT_LEFT_SHIP_POINTS
		CALL UPDATE_TEXT_RIGHT_SHIP_POINTS

		MOV GAME_ACTIVE, 02H

		CALL RETURN_KEY

		CMP AL, 'R'

		JE RESTART_GAME_2

		CMP AL, 'r'

		JE RESTART_GAME_2
		
		CMP AL, 'M'
		
		JE MAIN_MENU_2

		CMP AL, 'm'
		
		JE MAIN_MENU_2

		RET

		RESTART_GAME_2:

			MOV GAME_ACTIVE, 01H

			RET		

		MAIN_MENU_2:

			MOV GAME_ACTIVE  , 00H
			MOV CURRENT_SCENE, 00H

			CALL DRAW_MAIN_MENU

			RET

	DRAW_HAPPY_BIRTHDAY ENDP

CODE ENDS

END